language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "7"
  - "6.4.0"
  - "6"
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database audigo_test;' -U postgres
after_success:
  - npm run sendcoverage
